export default function Head() {
  return (
    <>
      <title>Create Next App</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" type="image/svg+xml" href="/favicon/favicon.svg" />
      <link rel="icon" type="image/png" href="/favicon/favicon.png" />
    </>
  );
}
